## 1. Elementwise Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [1]:
import numpy as np

In [2]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[9,8,7]])

In [6]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[1, 2, 3],
        [9, 8, 7]]))

### Arithmetic Operations

In [7]:
# a + b 
np.add(a,b)

array([[ 5,  7,  9],
       [14, 15, 16]])

In [30]:
# a-b
np.subtract(a,b)

array([[ 3,  3,  3],
       [-4, -1,  2]])

In [11]:
# a * b
np.multiply(a,b)

array([[ 4, 10, 18],
       [45, 56, 63]])

In [20]:
# a ** 2
# np.square(b)
np.power(a,b)

array([[      4,      25,     216],
       [1953125, 5764801, 4782969]])

In [21]:
# a % b
quo, rem = np.divmod(a,2)

In [22]:
rem

array([[0, 1, 0],
       [1, 1, 1]])

In [27]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [35]:
np.ceil(np.sqrt(a))

array([[2., 3., 3.],
       [3., 3., 3.]])

### Trignometric

In [36]:
new = 1 / np.sin(a)
print(new)

[[-1.32134871 -1.04283521 -3.57889955]
 [-1.04283521  1.52210106  2.42648664]]


In [37]:
1 / np.tan(b)

array([[ 0.64209262, -0.45765755, -7.01525255],
       [-2.21084541, -0.14706506,  1.14751542]])

### Rounding operations

In [39]:
np.round(new, decimals=3)

array([[-1.321, -1.043, -3.579],
       [-1.043,  1.522,  2.426]])

In [40]:
np.around(new, decimals=3)

array([[-1.321, -1.043, -3.579],
       [-1.043,  1.522,  2.426]])

In [46]:
np.fix(new)

array([[-1., -1., -3.],
       [-1.,  1.,  2.]])

In [42]:
np.floor(new)

array([[-2., -2., -4.],
       [-2.,  1.,  2.]])

## 2. Matrix Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [54]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[1,2,3],[9,8,7], [9,4,7]])

b

array([[1, 2, 3],
       [9, 8, 7],
       [9, 4, 7]])

In [50]:
np.dot(a,b)

array([[103,  72,  89],
       [149, 102, 127]])

In [52]:
# b.T
np.transpose(b)

array([[1, 9, 9],
       [2, 8, 4],
       [3, 7, 7]])

In [55]:
np.trace(b)

np.int64(16)

In [57]:
np.linalg.det(b)

np.float64(-79.99999999999997)

In [61]:
# B . B-1 = I
np.dot(
    b, np.linalg.inv(b)
).round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [65]:
# Solve Equations: x + 2*y = 1 and 3*x + 5*y = 2
a = np.array([[1,2],
              [3,5]])
b = np.array([1,2])

In [68]:
np.linalg.solve(a, b)

array([-1.,  1.])