## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [14]:
import numpy as np

In [15]:
arr = np.random.randint(10,50, size = (5,2,3))

In [4]:
arr.shape

(5, 2, 3)

In [5]:
arr.ndim

3

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr_T = arr.T
arr_T

array([[[34, 18, 39, 16, 48],
        [22, 27, 26, 38, 31]],

       [[13, 42, 41, 41, 24],
        [16, 44, 41, 10, 14]],

       [[34, 18, 35, 24, 47],
        [28, 16, 35, 11, 34]]])

In [8]:
arr_T.shape

(3, 2, 5)

In [9]:
arr.shape

(5, 2, 3)

In [10]:
arr.reshape(3,5,2)

array([[[34, 13],
        [34, 22],
        [16, 28],
        [18, 42],
        [18, 27]],

       [[44, 16],
        [39, 41],
        [35, 26],
        [41, 35],
        [16, 41]],

       [[24, 38],
        [10, 11],
        [48, 24],
        [47, 31],
        [14, 34]]])

In [12]:
arr.reshape(-1,2,3)

array([[[34, 13, 34],
        [22, 16, 28]],

       [[18, 42, 18],
        [27, 44, 16]],

       [[39, 41, 35],
        [26, 41, 35]],

       [[16, 41, 24],
        [38, 10, 11]],

       [[48, 24, 47],
        [31, 14, 34]]])

In [27]:
arr.flatten()

array([36, 12, 12, 34, 23, 27, 13, 11, 42, 13, 37, 28, 22, 23, 34, 16, 20,
       39, 28, 42, 20, 39, 40, 36, 35, 14, 37, 31, 25, 23])

### 0 > column wise
### 1 > row wise

In [49]:
# arr.sum()
arr.sum(axis = 1)


array([[70, 35, 39],
       [26, 48, 70],
       [38, 43, 73],
       [67, 82, 56],
       [66, 39, 60]])

In [39]:
np.sum(
    [
        [0, 1], 
        [0, 5]
    ], 
axis=0)


array([0, 6])

In [40]:
np.sum(
    [
        [0, 1], 
        [0, 5]
    ], 
axis=1)


array([1, 5])

In [45]:
arr.prod(dtype = float)

np.float64(8.114461873681362e+41)

In [46]:
arr.prod(axis = 0)

array([[10090080,  1785168, 12680640],
       [ 8550048, 17020000, 24412752]])

In [47]:
arr.cumsum()

array([ 36,  48,  60,  94, 117, 144, 157, 168, 210, 223, 260, 288, 310,
       333, 367, 383, 403, 442, 470, 512, 532, 571, 611, 647, 682, 696,
       733, 764, 789, 812])

In [55]:
arr.max()

np.int64(42)

In [58]:
arr.argmax()
# arr.argmax(axis = 0)

np.int64(8)

In [60]:
arr.clip(10,20)

array([[[20, 12, 12],
        [20, 20, 20]],

       [[13, 11, 20],
        [13, 20, 20]],

       [[20, 20, 20],
        [16, 20, 20]],

       [[20, 20, 20],
        [20, 20, 20]],

       [[20, 14, 20],
        [20, 20, 20]]])

In [77]:
arr1 = np.random.randint(low = -10, high = 10, size = (2,3))
arr2 = np.random.randint(low = 0, high = 11, size = (2,3))

In [78]:
arr1, arr2

(array([[-3, -8, -2],
        [ 4, -3,  2]]),
 array([[ 2,  8,  2],
        [ 3,  1, 10]]))

In [81]:
np.vstack([arr1, arr2]) #< same columns

array([[-3, -8, -2],
       [ 4, -3,  2],
       [ 2,  8,  2],
       [ 3,  1, 10]])

In [80]:
np.hstack((arr1, arr2)) #< same rows

array([[-3, -8, -2,  2,  8,  2],
       [ 4, -3,  2,  3,  1, 10]])