In [2]:
!pip install numpy 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 27.9 MB/s eta 0:00:00m eta 0:00:010:01:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.2 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.2 which is incompatible.


In [3]:
import numpy as np

## Creating Numpy Array

In [5]:
list1 = [2,3,4]

arr1 = np.array(list1)

In [6]:
arr1

array([2, 3, 4])

In [7]:
arr1.shape

(3,)

In [15]:
arr1.ndim

1

In [27]:
list2 = [[1,5,9],
         [6,8,2],
         [6,9,3],
         [6,2,4]]
arr2 = np.array(list2)

In [28]:
arr2

array([[1, 5, 9],
       [6, 8, 2],
       [6, 9, 3],
       [6, 2, 4]])

In [29]:
arr2.shape

(4, 3)

In [30]:
arr2.ndim

2

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [37]:
np.zeros(shape = (5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones(shape = (4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
np.full((2,2), 7.8)

array([[7.8, 7.8],
       [7.8, 7.8]])

In [45]:
np.random.rand(2,3)

array([[0.25290194, 0.76830632, 0.63322382],
       [0.84996208, 0.34493012, 0.06003046]])

In [55]:
np.random.randint(low = 4, high = 30, size = (2,2))

array([[15,  7],
       [29, 25]])

In [49]:
np.linspace(start = 0, stop = 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
np.linspace(start = (0,1,2) , stop = (10,20,30), num=5, axis=0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])